// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj   = require("bs-platform/lib/js/caml_obj.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function unwrap(a) {
  if (a) {
    return a[0];
  } else {
    return Pervasives.failwith("Unexpected None");
  }
}

function is(x, y) {
  return +(x === y);
}

var equals = Caml_obj.caml_equal;

function test(msg, b) {
  if (b) {
    console.log("✅  " + (String(msg) + ""));
    return /* () */0;
  } else {
    console.log("🚫  " + (String(msg) + ""));
    return /* () */0;
  }
}

exports.unwrap = unwrap;
exports.is     = is;
exports.equals = equals;
exports.test   = test;
/* No side effect */
