// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var P01$NineNine = require("./p01.bs.js");
var P02$NineNine = require("./p02.bs.js");
var P03$NineNine = require("./p03.bs.js");
var P04$NineNine = require("./p04.bs.js");
var P05$NineNine = require("./p05.bs.js");
var P06$NineNine = require("./p06.bs.js");

P01$NineNine.run(/* () */0);

P02$NineNine.run(/* () */0);

P03$NineNine.run(/* () */0);

P04$NineNine.run(/* () */0);

P05$NineNine.run(/* () */0);

P06$NineNine.run(/* () */0);

/*  Not a pure module */
