// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List             = require("bs-platform/lib/js/list.js");
var Helpers$NineNine = require("./helpers.bs.js");

function last(l) {
  if (l) {
    return /* Some */[List.nth(l, List.length(l) - 1 | 0)];
  } else {
    return /* None */0;
  }
}

function run() {
  Helpers$NineNine.test("Gets the last item", +(Helpers$NineNine.unwrap(last(/* :: */[
                  "a",
                  /* :: */[
                    "b",
                    /* :: */[
                      "c",
                      /* :: */[
                        "d",
                        /* [] */0
                      ]
                    ]
                  ]
                ])) === "d"));
  return Helpers$NineNine.test("Returns None if empty", +(last(/* [] */0) === /* None */0));
}

exports.last = last;
exports.run  = run;
/* No side effect */
