// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List             = require("bs-platform/lib/js/list.js");
var Helpers$NineNine = require("./helpers.bs.js");

function lastTwo(l) {
  if (l && l[1]) {
    return /* Some */[List.nth(l, List.length(l) - 2 | 0)];
  } else {
    return /* None */0;
  }
}

function run() {
  Helpers$NineNine.test("Gets the second last", +(Helpers$NineNine.unwrap(lastTwo(/* :: */[
                  "a",
                  /* :: */[
                    "b",
                    /* :: */[
                      "c",
                      /* :: */[
                        "d",
                        /* [] */0
                      ]
                    ]
                  ]
                ])) === "c"));
  Helpers$NineNine.test("None if none", +(lastTwo(/* [] */0) === /* None */0));
  return Helpers$NineNine.test("None if one", +(lastTwo(/* :: */[
                    "a",
                    /* [] */0
                  ]) === /* None */0));
}

exports.lastTwo = lastTwo;
exports.run     = run;
/* No side effect */
