// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List             = require("bs-platform/lib/js/list.js");
var Helpers$NineNine = require("./helpers.bs.js");

function at(n, xs) {
  if (List.length(xs) >= n) {
    return /* Some */[List.nth(xs, n - 1 | 0)];
  } else {
    return /* None */0;
  }
}

function run() {
  Helpers$NineNine.test("Gets the 3rd element", Helpers$NineNine.is("c", Helpers$NineNine.unwrap(at(3, /* :: */[
                    "a",
                    /* :: */[
                      "b",
                      /* :: */[
                        "c",
                        /* :: */[
                          "d",
                          /* :: */[
                            "e",
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]))));
  return Helpers$NineNine.test("Gets None if less than n elements", Helpers$NineNine.is(/* None */0, at(3, /* :: */[
                      "a",
                      /* [] */0
                    ])));
}

exports.at  = at;
exports.run = run;
/* No side effect */
