// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Helpers$NineNine = require("./helpers.bs.js");

function length(xs) {
  if (xs) {
    return 1 + length(xs[1]) | 0;
  } else {
    return 0;
  }
}

function run() {
  Helpers$NineNine.test("Gets length of 3", Helpers$NineNine.is(3, length(/* :: */[
                "a",
                /* :: */[
                  "b",
                  /* :: */[
                    "c",
                    /* [] */0
                  ]
                ]
              ])));
  return Helpers$NineNine.test("Gets length of 0", Helpers$NineNine.is(0, 0));
}

exports.length = length;
exports.run    = run;
/* No side effect */
