// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var List             = require("bs-platform/lib/js/list.js");
var Caml_obj         = require("bs-platform/lib/js/caml_obj.js");
var Helpers$NineNine = require("./helpers.bs.js");

function isPalindrome(xs) {
  return Caml_obj.caml_equal(xs, List.rev(xs));
}

function run() {
  Helpers$NineNine.test("Detects if it is", Helpers$NineNine.is(/* true */1, Caml_obj.caml_equal(/* :: */[
                "x",
                /* :: */[
                  "a",
                  /* :: */[
                    "m",
                    /* :: */[
                      "a",
                      /* :: */[
                        "x",
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ], List.rev(/* :: */[
                    "x",
                    /* :: */[
                      "a",
                      /* :: */[
                        "m",
                        /* :: */[
                          "a",
                          /* :: */[
                            "x",
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]))));
  return Helpers$NineNine.test("Detects if it is not", Helpers$NineNine.is(/* false */0, Caml_obj.caml_equal(/* :: */[
                      "a",
                      /* :: */[
                        "b",
                        /* [] */0
                      ]
                    ], List.rev(/* :: */[
                          "a",
                          /* :: */[
                            "b",
                            /* [] */0
                          ]
                        ]))));
}

exports.isPalindrome = isPalindrome;
exports.run          = run;
/* No side effect */
